name: 'Repo Trust'
description: 'Publish a verified download page to GitHub Pages to protect users from repo squatting attacks'
author: 'Repo Trust'

branding:
  icon: 'shield'
  color: 'green'

runs:
  using: 'docker'
  image: 'Dockerfile'
