name: Repo Trust

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Repo Trust
        uses: repo-trust/repo-trust@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
